// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAk_bxD5nbQaLcUKV6itVxaok7BAQXj_E',
    appId: '1:291465152511:web:a52e24038cb69df70549ca',
    messagingSenderId: '291465152511',
    projectId: 'smart-subscription-tracker-app',
    authDomain: 'smart-subscription-tracker-app.firebaseapp.com',
    storageBucket: 'smart-subscription-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZPaVbfXhDf7qvYALiZWUYC2OUh3gSrzk',
    appId: '1:291465152511:android:96c3bb11c1e5006f0549ca',
    messagingSenderId: '291465152511',
    projectId: 'smart-subscription-tracker-app',
    storageBucket: 'smart-subscription-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClLDMJIP-rEzPq57gEX3g6uIP1YysYRjA',
    appId: '1:291465152511:ios:0deb904fd88421eb0549ca',
    messagingSenderId: '291465152511',
    projectId: 'smart-subscription-tracker-app',
    storageBucket: 'smart-subscription-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.smartSubscriptionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClLDMJIP-rEzPq57gEX3g6uIP1YysYRjA',
    appId: '1:291465152511:ios:0deb904fd88421eb0549ca',
    messagingSenderId: '291465152511',
    projectId: 'smart-subscription-tracker-app',
    storageBucket: 'smart-subscription-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.smartSubscriptionTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAk_bxD5nbQaLcUKV6itVxaok7BAQXj_E',
    appId: '1:291465152511:web:20b97888b36eb22c0549ca',
    messagingSenderId: '291465152511',
    projectId: 'smart-subscription-tracker-app',
    authDomain: 'smart-subscription-tracker-app.firebaseapp.com',
    storageBucket: 'smart-subscription-tracker-app.firebasestorage.app',
  );
}